#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Sinh ../assets/thanh-ngu.json. Chạy một lần; giữ lại để bản chọn lọc có đường lần ngược:
ai muốn kiểm phép lọc thì đọc file này, không phải đoán từ kết quả."""
import json
from pathlib import Path

E = [
    ("dây cà ra dây muống", "Nói dài dòng, chuyện này bắt sang chuyện khác, không về đích.",
     "Nhận xét một đoạn văn hoặc một phần trình bày lan man; dùng khi đang nói về cách viết.",
     ["essay", "blog"]),
    ("có ít xít ra nhiều", "Thổi phồng một sự việc nhỏ thành lớn.",
     "Phê phán cách trưng số liệu hoặc kết quả vượt quá điều dữ liệu đỡ được.",
     ["essay", "blog", "journalism", "chinh-luan"]),
    ("cả vú lấp miệng em", "Dùng thế mạnh của mình át tiếng người yếu thế hơn.",
     "Bàn về tranh luận không cân sức, về cách một bên áp đảo diễn đàn.",
     ["essay", "blog", "chinh-luan"]),
    ("cò kè bớt một thêm hai", "Mặc cả đi mặc cả lại từng chút một.",
     "Mô tả quá trình thương lượng kéo dài; hợp với bài kể lại đàm phán, dự toán, hợp đồng.",
     ["blog", "journalism"]),
    ("cái quan định luận", "Đậy nắp quan tài rồi mới định được công tội; chỉ khi việc đã xong mới đánh giá được.",
     "Nhắc rằng đánh giá quá sớm là đánh giá thiếu dữ kiện; hợp với bài bàn về tổng kết, di sản, hậu thế.",
     ["essay", "chinh-luan"]),
    ("đan gàu tát biển", "Bỏ công vào một việc không thể đạt kết quả.",
     "Chỉ ra sự chênh lệch giữa nguồn lực bỏ ra và quy mô vấn đề.",
     ["essay", "blog", "chinh-luan"]),
    ("con kiến kiện củ khoai", "Người yếu thế theo đuổi một vụ việc mà mình không có cửa thắng.",
     "Bàn về khoảng cách quyền lực trong khiếu nại, tố tụng, khiếu kiện hành chính.",
     ["essay", "journalism", "chinh-luan"]),
    ("bảo hoàng hơn nhà vua", "Nhiệt tình bảo vệ một chủ trương còn hơn cả người đề ra nó.",
     "Phê phán việc thi hành cứng nhắc quá mức yêu cầu; rất hợp khi bàn về triển khai chính sách.",
     ["essay", "blog", "journalism", "chinh-luan"]),
    ("dân sinh quốc kế", "Việc làm ăn của dân và việc lo tính của Nhà nước.",
     "Cụm Hán Việt trang trọng, dùng khi nêu phạm vi ảnh hưởng của một chính sách.",
     ["chinh-luan", "bao-cao-thuc-tap"]),
    ("ba mũi giáp công", "Đánh vào một mục tiêu từ ba hướng cùng lúc.",
     "Mô tả một giải pháp có ba nhánh phối hợp; chỉ dùng khi thật sự có đúng ba nhánh.",
     ["chinh-luan", "sang-kien-kinh-nghiem", "bao-cao-thuc-tap"]),
    ("Bạt núi ngăn sông", "Sức mạnh và khí thế phi thường; việc lớn lao.",
     "Chỉ dùng khi quy mô thật sự lớn. Đây là cụm dễ thành lời nói quá — xem cảnh báo.",
     ["chinh-luan"]),
    ("chưa qua cầu đã cất nhịp", "Cản người ta ngay khi việc của họ còn dang dở.",
     "Bàn về việc rút hỗ trợ giữa chừng, cắt nguồn lực khi dự án chưa xong.",
     ["essay", "blog", "journalism"]),
    ("Té nước theo mưa", "Nhân lúc có biến mà kiếm lợi cho mình.",
     "Phê phán hành vi ăn theo một sự kiện; hợp với bài bình luận thị trường, truyền thông.",
     ["blog", "journalism", "chinh-luan"]),
    ("Mềm nắn rắn buông", "Đối xử tuỳ đối tượng: lấn người yếu, nhường người cứng.",
     "Chỉ ra sự thiếu nhất quán trong thực thi quy định.",
     ["essay", "journalism", "chinh-luan"]),
    ("Thuốc đắng dã tật", "Biện pháp khó chịu nhưng chữa được gốc bệnh.",
     "Mở đường cho một đề xuất bị phản đối vì khó thực hiện.",
     ["essay", "blog", "chinh-luan", "sang-kien-kinh-nghiem"]),
    ("Chín bỏ làm mười", "Xuê xoa, bỏ qua cho nhau để giữ hoà khí.",
     "Phê phán việc nới tiêu chuẩn vì nể nang; hợp với bài về đánh giá, nghiệm thu, chấm điểm.",
     ["essay", "blog", "bao-cao-thuc-tap"]),
    ("Sống lâu lên lão làng", "Được cất nhắc nhờ thâm niên chứ không nhờ năng lực.",
     "Bàn về tiêu chí đề bạt, về cơ chế đánh giá cán bộ.",
     ["essay", "journalism", "chinh-luan"]),
    ("Mua danh ba vạn, bán danh ba đồng", "Gây dựng uy tín rất tốn, đánh mất thì rất nhanh.",
     "Nói về rủi ro danh tiếng của một tổ chức hoặc một nghề.",
     ["essay", "blog", "journalism"]),
    ("Lao tâm khổ tứ", "Lo nghĩ nhiều, dốc sức suy tính.",
     "Ghi nhận công sức bỏ ra; cụm trang trọng, hợp phần cảm ơn hoặc phần nhìn lại.",
     ["essay", "bao-cao-thuc-tap", "sang-kien-kinh-nghiem"]),
    ("ăn cơm nhà, thổi tù và hàng tổng", "Bỏ công sức và chi phí của mình để làm việc chung.",
     "Nói về công việc kiêm nhiệm không thù lao, về người vác tù và hàng tổng ở cơ sở.",
     ["blog", "journalism", "bao-cao-thuc-tap"]),
    ("cửa Khổng, sân Trình", "Cửa nhà Nho, chỉ nền học vấn Nho giáo.",
     "Chỉ dùng khi thật sự bàn về truyền thống khoa cử, không dùng thay cho chữ 'nhà trường'.",
     ["essay", "chinh-luan"]),
    ("Hạ bút thành chương", "Đặt bút xuống là ra bài, viết rất nhanh và rất trôi.",
     "Khen năng lực viết; cũng dùng ngược để nói về văn trôi mà rỗng.",
     ["essay", "blog"]),
    ("Dương dương đắc ý", "Vênh váo, ra vẻ đắc thắng.",
     "Mô tả thái độ của một bên sau khi thắng thế; giọng phê phán rõ, cân nhắc ở văn trang trọng.",
     ["essay", "blog", "journalism"]),
    ("Bần thanh hơn phú trọc", "Nghèo mà trong sạch hơn giàu mà đục.",
     "Nêu một lựa chọn giá trị; hợp bài bàn về liêm chính.",
     ["essay", "chinh-luan"]),
    ("Chen vai thích cánh", "Chen chúc, đua nhau giành phần.",
     "Mô tả cảnh cạnh tranh đông đúc: tuyển sinh, xin việc, giành suất.",
     ["essay", "blog", "journalism"]),
    ("Ngang tai chướng mắt", "Khó chịu vì lời nói hoặc việc làm trái lẽ thường.",
     "Nêu phản ứng của người trong cuộc trước một quyết định; là nhận định chủ quan, cần kèm dữ kiện.",
     ["blog", "journalism"]),
    ("bẻ đũa cả nắm", "Chống lại cả một số đông cùng lúc, không biết phân biệt.",
     "Phê phán cách quy kết cả nhóm; gần với lỗi vơ đũa cả nắm trong lập luận.",
     ["essay", "blog", "chinh-luan"]),
    ("ba mươi sáu chước", "Trong ba mươi sáu kế thì rút lui là hơn cả.",
     "Nói về quyết định dừng lại, rút khỏi một cuộc chơi không có lợi.",
     ["blog", "journalism"]),
    ("ba tấc lưỡi", "Chỉ tài dùng lời nói để thuyết phục.",
     "Bàn về sức mạnh và giới hạn của diễn ngôn; thường mang sắc thái cảnh giác.",
     ["essay", "blog", "chinh-luan"]),
    ("cây nhà lá vườn", "Thứ sẵn có trong nhà, tự làm lấy, không mua ngoài.",
     "Nói về giải pháp tự làm, nguồn lực tại chỗ; giọng khiêm nhường.",
     ["blog", "bao-cao-thuc-tap", "sang-kien-kinh-nghiem"]),
    ("Rán sành ra mỡ", "Đòi kết quả từ chỗ không thể có; cũng chỉ người hà tiện quá mức.",
     "Phê phán yêu cầu vượt quá năng lực nguồn lực đã cấp.",
     ["essay", "blog", "bao-cao-thuc-tap"]),
    ("Chạy long tóc gáy", "Chạy ngược chạy xuôi lo cho xong việc gấp.",
     "Kể lại giai đoạn gấp rút; giọng đời thường, hợp blog và phần kể trong báo cáo.",
     ["blog", "bao-cao-thuc-tap"]),
    ("Chạy thầy chạy thợ", "Tìm mọi nơi, mọi cách để chữa hoặc gỡ một việc.",
     "Mô tả nỗ lực tuyệt vọng trước một sự cố.",
     ["blog", "journalism"]),
    ("của một đồng, công một nén", "Giá trị món đồ thì nhỏ, công sức bỏ ra thì lớn.",
     "Nói về chi phí ẩn, về công sức không hiện trong dự toán.",
     ["essay", "blog", "bao-cao-thuc-tap"]),
    ("Ra tấm ra miếng", "Rành mạch, đâu ra đấy, đủ lớn để dùng được.",
     "Đặt chuẩn cho một kết quả: phải đủ tầm chứ không phải làm cho có.",
     ["blog", "bao-cao-thuc-tap", "sang-kien-kinh-nghiem"]),
    ("Quen ăn bén mùi", "Được lợi một lần rồi quen, lặp lại thủ đoạn cũ.",
     "Chỉ ra tính lặp của một hành vi trục lợi.",
     ["journalism", "chinh-luan"]),
    ("Người ba đấng, của ba loài", "Người có tốt có xấu, của có thứ hay thứ dở.",
     "Chặn lối khái quát cả một nhóm từ vài trường hợp; dùng khi phản bác quy chụp.",
     ["essay", "blog", "chinh-luan"]),
    ("Chim khôn thử tiếng, người ngoan thử lời", "Qua lời ăn tiếng nói biết được người.",
     "Mở một đoạn bàn về vai trò của ngôn ngữ trong đánh giá con người.",
     ["essay", "blog"]),
    ("Dao sắc không bằng chắc kê", "Dụng cụ tốt không bằng chỗ tựa vững.",
     "Nói rằng nền tảng quan trọng hơn công cụ; hợp bài về hạ tầng, quy trình, dữ liệu nền.",
     ["essay", "blog", "sang-kien-kinh-nghiem"]),
    ("Không tuần chay nào thiếu nước mắt", "Việc gì cũng có mặt, chỗ nào cũng góp phần.",
     "Nhận xét một cái tên xuất hiện ở mọi hồ sơ, mọi gói thầu, mọi hội đồng.",
     ["journalism", "chinh-luan"]),
    ("Nước sông công lính", "Thứ sẵn có và công sức người khác thì bị dùng tuỳ tiện.",
     "Phê phán việc tiêu nguồn lực chung như thể nó vô hạn.",
     ["essay", "journalism", "chinh-luan"]),
    ("Đá đưa đầu lưỡi", "Nói năng đong đưa, khôn khéo mà không thật.",
     "Mô tả cách trả lời né tránh; là nhận định về thái độ, phải kèm câu trích.",
     ["journalism", "chinh-luan"]),
    ("Bút Nam Tào, dao thày thuốc", "Ngòi bút và con dao đều định đoạt số phận người khác.",
     "Nói về trách nhiệm của người cầm bút và người có quyền quyết định.",
     ["essay", "journalism", "chinh-luan"]),
    ("Sơn ăn tuỳ mặt, ma bắt tuỳ người", "Cùng một thứ nhưng tác động khác nhau tuỳ người.",
     "Giải thích vì sao một chính sách chung lại có kết quả rất khác giữa các nhóm.",
     ["essay", "chinh-luan", "sang-kien-kinh-nghiem"]),
    ("có thủy có chung", "Trước sau như một, giữ trọn tình nghĩa.",
     "Ghi nhận sự nhất quán, thường ở phần cảm ơn hoặc phần nhìn lại.",
     ["essay", "bao-cao-thuc-tap"]),
    ("bán đồ nhi phế", "Nửa đường bỏ dở.",
     "Cụm Hán Việt trang trọng cho việc dừng giữa chừng; hợp phần đánh giá dự án.",
     ["essay", "chinh-luan", "bao-cao-thuc-tap"]),
    ("Ngậm ngải tìm trầm", "Chịu gian khổ và rủi ro lớn để tìm một thứ quý hiếm.",
     "Mô tả một hành trình theo đuổi dài và bấp bênh.",
     ["essay", "blog"]),
    ("Tiếng bấc tiếng chì", "Lời qua tiếng lại, khi nhẹ khi nặng.",
     "Mô tả một cuộc tranh cãi kéo dài giữa hai bên.",
     ["blog", "journalism"]),
    ("Trăm kẻ bán, vạn người mua", "Người bán đông thì người mua cũng đông.",
     "Nói về một thị trường có đủ hai phía, không lo ế.",
     ["blog", "journalism"]),
    ("Của trọng người khinh", "Coi tiền bạc nặng hơn tình nghĩa và con người.",
     "Phê phán một cách sắp thứ tự ưu tiên.",
     ["essay", "chinh-luan"]),
    ("Lời hay lẽ phải", "Lời khuyên đúng, phân tích rõ phải trái.",
     "Cụm trung tính, dùng khi nhắc tới việc thuyết phục bằng lý lẽ.",
     ["essay", "blog", "chinh-luan"]),
    ("Kén chọn lọc lừa", "Chọn quá kỹ, cầu kỳ đến mức bỏ lỡ.",
     "Nói về khâu tuyển chọn quá chặt so với nguồn ứng viên thực có.",
     ["blog", "bao-cao-thuc-tap"]),
    ("Miệng ông cai, vai đầy tớ", "Nói thì như người có quyền, làm thì như người làm thuê.",
     "Chỉ ra khoảng cách giữa lời tuyên bố và vị thế thực tế.",
     ["essay", "journalism", "chinh-luan"]),
    ("Sóng trước bổ sao, sóng sau bổ vậy", "Người trước làm thế nào thì người sau theo thế ấy.",
     "Nói về sức nặng của tiền lệ và của việc nêu gương.",
     ["essay", "chinh-luan", "sang-kien-kinh-nghiem"]),
    ("Vắng sao Hôm, có sao Mai", "Thiếu người này thì có người khác thay.",
     "Nói về khả năng thay thế trong một hệ thống; cũng dùng ngược để chỉ sự lệ thuộc vào cá nhân.",
     ["blog", "journalism", "bao-cao-thuc-tap"]),
    ("Xôi giả vạ thật", "Lợi thì hão mà hoạ thì có thật.",
     "Cân nhắc rủi ro so với lợi ích của một phương án.",
     ["essay", "blog", "chinh-luan"]),
    ("Cá kể đầu, rau kể mớ", "Đếm cho đủ số, không phân biệt lớn nhỏ, không chọn lọc.",
     "Phê phán việc chạy theo số lượng trong báo cáo thành tích.",
     ["essay", "journalism", "bao-cao-thuc-tap"]),
    ("Đếm bụt đóng oản", "Liệu đúng số người mà làm, không thừa không thiếu.",
     "Nói về việc lập kế hoạch bám sát nhu cầu thực.",
     ["blog", "bao-cao-thuc-tap", "sang-kien-kinh-nghiem"]),
]

WARN = {
    "Bạt núi ngăn sông": "Cụm nói quá. Dùng cho một việc quy mô vừa là rơi thẳng vào T01 (thổi phồng tầm quan trọng).",
    "cửa Khổng, sân Trình": "Điển cố. Người đọc không biết điển thì câu mất nghĩa; chỉ dùng khi ngữ cảnh đã nói về Nho học.",
    "Dương dương đắc ý": "Gán thái độ cho người khác. Phải có câu trích hoặc hành vi quan sát được đỡ, nếu không là quy chụp.",
    "Đá đưa đầu lưỡi": "Gán động cơ xảo trá. Cần câu trích cụ thể, nếu không thì đây là công kích cá nhân.",
    "Không tuần chay nào thiếu nước mắt": "Ám chỉ trục lợi. Ở bài báo chí phải có bằng chứng, không dùng như một câu bóng gió.",
    "ba mươi sáu chước": "Nghĩa gốc là 'chạy đi là hơn cả'. Dùng sai thành 'nhiều mưu kế' là lệch nghĩa.",
    "Chín bỏ làm mười": "Sắc thái phê phán. Ở báo cáo nội bộ có thể bị đọc thành chỉ trích đồng nghiệp.",
    "cái quan định luận": "Điển Hán Việt nặng. Ở blog phổ thông nên diễn giải kèm.",
}

out = {
    "schema_version": "1.0",
    "updated": "2026-08-30",
    "purpose": (
        "Tập con có chọn lọc, dùng cho trục 4 khi bản thảo cần một cụm cố định thay cho "
        "một câu giải thích dài. KHÔNG phải danh sách phải dùng, và tuyệt đối không phải "
        "danh sách rắc vào bài cho 'giống người viết hơn'."
    ),
    "attribution": {
        "source_repo": "https://github.com/ReML-AI/VIVID",
        "license": "MIT",
        "repo_commit": "634320b8e5d2e470f55391fe8036378d951c7c21",
        "source_file": "dataset/VIVID_Dataset.csv",
        "source_file_blob_sha": "9d114a4e99baa2cc87d56eea511c57912a8c6704",
        "checked": "2026-08-30",
        "note": (
            "Chỉ mượn DANH SÁCH thành ngữ. Cột nghĩa, ngữ cảnh dùng và thể loại phù hợp "
            "trong file này do repo này tự soạn, không chép nguyên văn cột Meaning của bộ dữ liệu."
        ),
    },
    "selection": {
        "source_total": 1636,
        "selected": len(E),
        "criteria_keep": [
            "Từ vựng còn dùng trong tiếng Việt hôm nay, người đọc phổ thông hiểu không cần chú thích dài",
            "Nghĩa nói được về công việc, tổ chức, chính sách, học thuật hoặc cách viết",
            "Đứng được trong một câu văn trang trọng mà không tụt giọng xuống khẩu ngữ",
        ],
        "criteria_drop": [
            "Cần kiến thức nhà nông, nghề cũ hoặc phong tục cũ mới hiểu (phần lớn bộ dữ liệu rơi vào đây)",
            "Từ vựng cổ hoặc phương ngữ hẹp",
            "Hạ thấp người theo giới, tuổi, nghề nghiệp hoặc ngoại hình",
            "Nói về tình duyên, ma chay, cỗ bàn, rượu chè — lệch chủ đề của repo",
            "Trùng nghĩa với một mục đã chọn",
        ],
        "honest_note": (
            "Bộ dữ liệu nguồn là kho thành ngữ hiếm và cổ, dựng cho bài toán đo độ khó ngôn ngữ, "
            "không phải kho thành ngữ thông dụng. Vì vậy tỷ lệ dùng được cho văn học thuật và blog "
            "rất thấp: giữ 58 trên 1.636. Con số này là kết quả thật của phép lọc, không phải hạn "
            "ngạch. Không nới tiêu chí để đạt một con số đẹp hơn."
        ),
    },
    "usage_rules": [
        "Chỉ dùng khi thành ngữ THAY THẾ được một câu giải thích dài hơn. Thêm vào một câu đã đủ nghĩa là làm câu nặng thêm.",
        "Tối đa một thành ngữ cho mỗi phần lớn của bài. Rắc dày là một dáng văn máy khác, không phải giọng người.",
        "KHÔNG dùng ở thể loại research và de-cuong-nghien-cuu: §4 của research.md cấm thêm sắc thái đánh giá vào Kết quả và Phương pháp.",
        "KHÔNG dùng thành ngữ để thay cho một con số hoặc một nguồn còn thiếu.",
        "Thành ngữ do trục 4 thêm vào là một nhát sửa: phải có dòng trong polish.diff.json với reason nói rõ nó thay thế điều gì.",
        "Writer profile thắng file này. Người viết không dùng thành ngữ bao giờ thì đừng thêm thành ngữ cho họ.",
    ],
    "the_loai_hop_le": [
        "essay", "blog", "journalism", "chinh-luan", "bao-cao-thuc-tap", "sang-kien-kinh-nghiem",
    ],
    "entries": [],
}

for i, (thanh_ngu, nghia, ngu_canh, the_loai) in enumerate(E, start=1):
    item = {
        "id": f"TN{i:03d}",
        "thanh_ngu": thanh_ngu,
        "nghia": nghia,
        "ngu_canh": ngu_canh,
        "the_loai": the_loai,
    }
    if thanh_ngu in WARN:
        item["canh_bao"] = WARN[thanh_ngu]
    out["entries"].append(item)

path = Path(__file__).resolve().parents[1] / "assets" / "thanh-ngu.json"
path.write_text(json.dumps(out, ensure_ascii=False, indent=1) + "\n", encoding="utf-8")
print(f"-> {path}  |  {len(out['entries'])} mục")
